# Generated by Django 3.0.5 on 2020-04-28 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('buildingCode', models.IntegerField(primary_key=True, serialize=False)),
                ('buildingType', models.CharField(choices=[('Unknown', 'unknown'), ('House', 'house'), ('Office', 'office')], default='unknown', max_length=10)),
                ('buildingImage', models.ImageField(upload_to='')),
                ('cost', models.IntegerField()),
                ('description', models.TextField()),
                ('size', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=20)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('location', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=40)),
                ('facebook_link', models.URLField()),
                ('twitter_link', models.URLField()),
                ('linkedIn_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planName', models.CharField(max_length=15)),
                ('image', models.ImageField(upload_to='')),
                ('description', models.TextField()),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appRadical.Building')),
            ],
        ),
        migrations.CreateModel(
            name='Components',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rooms', models.IntegerField(null=True)),
                ('bedrooms', models.IntegerField(null=True)),
                ('stories', models.IntegerField(null=True)),
                ('toilets', models.IntegerField(null=True)),
                ('kitchen', models.IntegerField(null=True)),
                ('store', models.IntegerField(null=True)),
                ('parkingSpace', models.IntegerField(null=True)),
                ('additional_features', models.TextField(null=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appRadical.Building')),
            ],
        ),
    ]
