# Generated by Django 3.0.5 on 2020-05-03 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appRadical', '0005_remove_purchase_amount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscribe',
        ),
    ]
