# Generated by Django 3.0.5 on 2020-05-21 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appRadical', '0006_delete_subscribe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='photo',
            field=models.ImageField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTVrSfGmoYYLtA6dvdV28JkxIT5125j2ma4KItQg06Tw19xfdX-&usqp=CAU', upload_to=''),
        ),
    ]
