# Generated by Django 3.0.5 on 2020-05-21 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appRadical', '0007_auto_20200521_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='photo',
            field=models.ImageField(default='https://webcomicms.net/sites/default/files/clipart/138435/person-icon-138435-7470593.svg', upload_to=''),
        ),
    ]
